[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
dusk_evm_testnet = "https://rpc.testnet.evm.dusk.network"
dusk_evm_mainnet = "https://rpc.evm.dusk.network"
